build_and_run:
	@fpc print-digits-of-number.pas
	@echo "\n"
	@./print-digits-of-number
	@rm print-digits-of-number.o print-digits-of-number

build:
	@fpc print-digits-of-number.pas
	@rm print-digits-of-number.o
